version: "3.0"

networks:
  api.network:

services:

  api:
    environment:
      - HTTP_ADDR=:8888
      - FILE_PATH=../../files
      - PG_URL=postgres://postgres:postgres@postgres/restapi?sslmode=disable
      - PG_MIGRATIONS_PATH=file://../../store/pg/migrations
      - LOG_LEVEL=debug
    #build: ./
    image: go_api:v1
    ports:
      - "8888"
    depends_on:
      - postgres
    networks:
      - "api.network"
    deploy:
      replicas: 2

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restapi
    volumes:
      - ./store/pg/data:/var/lib/postgresql/data
    networks:
      - "api.network"


  nginx:
        # specifies the latest nginx image
        image: nginx:latest
        # Connects the conf file of the container to the conf file in our folder
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        # It will start up the nginx only when all api containers have started
        depends_on: 
            - api
        # Connects the port 80 of the nginx container to localhost:80 or localhost
        ports: 
            - "80:80"
        networks: 
            - "api.network"